from machine import Pin


class Config:
    POINTER_PIN = 17
    RED_LED_PIN = 27
    GREEN_LED_PIN = 28
    BUTTON_PIN = 18

    LED_PIN_TYPE = Pin.OUT
    BUTTON_PIN_IN_TYPE = Pin.IN
    BUTTON_PIN_UP_TYPE = Pin.PULL_UP

    HORIZONTAL_SERVO_PIN = 0
    VERTICAL_SERVO_PIN = 1

    DIRECTION_FORWARD = 0
    DIRECTION_BACKWARD = 1

    FORWARD_SERVO_PWM_MIN = 10
    FORWARD_SERVO_PWM_MAX = 1000
    BACKWARD_SERVO_PWM_MIN = 3200
    BACKWARD_SERVO_PWM_MAX = 6000

    SERVO_MIN_WAIT = 0.01
    SERVO_MAX_WAIT = 1

    MAIN_LOOP_TRIGGER_WAIT = 0.5
